/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fri.cbw.MyTestModelTool1;

import fri.cbw.GenericTool.ToolTopComponent;
import fri.cbw.ToolGraph.ToolGraphSceneImpl;
import fri.cbw.ToolGraph.ToolWrapper;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.api.visual.graph.GraphScene;
import org.netbeans.api.visual.widget.general.IconNodeWidget;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//fri.cbw.MyTestModelTool1//MyTestModelTool//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "MyTestModelToolTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "fri.cbw.MyTestModelTool1.MyTestModelToolTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_MyTestModelToolAction",
preferredID = "MyTestModelToolTopComponent")
@Messages({
    "CTL_MyTestModelToolAction=MyTestModelTool",
    "CTL_MyTestModelToolTopComponent=MyTestModelTool Window",
    "HINT_MyTestModelToolTopComponent=This is a MyTestModelTool window"
})
public final class MyTestModelToolTopComponent extends ToolTopComponent {
    
    private DefaultTableModel speciesTableModel = new javax.swing.table.DefaultTableModel( new String [] { "Species" }, 0 );
    private DefaultTableModel reactionsTableModel = new javax.swing.table.DefaultTableModel(new String [] { "Reactants", "K", "Products" }, 0);;
    
    
    public MyTestModelToolTopComponent() {
        initComponents();
        setName(Bundle.CTL_MyTestModelToolTopComponent());
        setToolTipText(Bundle.HINT_MyTestModelToolTopComponent());
    }
    
    public String[] getSpeciesList(){
        Vector data = speciesTableModel.getDataVector();
        String[] list = new String[data.size()];
        
        for(int i = 0; i < data.size(); i++){
            list[i] = (String) ((Vector)data.get(i)).get(0);
        }
        
        return list;
    }
    
    private MyTestModelTool1 getMyTestModelTool(){
        try{
            ToolWrapper tw = (ToolWrapper)getScene().findObject (getToolNode());
            return (MyTestModelTool1) tw.getNodeGenericTool();
        }catch(ClassCastException e){
            Logger.getAnonymousLogger().severe(e.getMessage());
            e.printStackTrace();
        }
        return null;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProductsSum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldReactantsSum = new javax.swing.JTextField();
        jComboBoxSpecies1 = new javax.swing.JComboBox();
        jTextFieldProducts = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jComboBoxSpecies2 = new javax.swing.JComboBox();
        jTextFieldReactants = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelKOn = new javax.swing.JLabel();
        jTextFieldKOn = new javax.swing.JTextField();
        jComboBoxKOn = new javax.swing.JComboBox();
        jCheckBoxReversible = new javax.swing.JCheckBox();
        jLabelKOff = new javax.swing.JLabel();
        jTextFieldKOff = new javax.swing.JTextField();
        jComboBoxKOff = new javax.swing.JComboBox();
        jButtonDialogCancle = new javax.swing.JButton();
        jButtonDialogOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddSpecies = new javax.swing.JButton();
        jButtonDeleteSpecies = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReactions = new javax.swing.JTable();
        jButtonDeleteReaction = new javax.swing.JButton();
        jButtonAddReaction = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSpecies = new javax.swing.JTable();

        jDialog1.setTitle(org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jDialog1.title")); // NOI18N
        jDialog1.setMinimumSize(new java.awt.Dimension(540, 300));
        jDialog1.setModal(true);
        jDialog1.setResizable(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jLabel1.text")); // NOI18N

        jTextFieldProductsSum.setEditable(false);
        jTextFieldProductsSum.setText(org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jTextFieldProductsSum.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jLabel2.text")); // NOI18N

        jTextFieldReactantsSum.setEditable(false);
        jTextFieldReactantsSum.setText(org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jTextFieldReactantsSum.text")); // NOI18N

        jComboBoxSpecies1.setModel(
            new javax.swing.DefaultComboBoxModel(getSpeciesList())
        );
        jComboBoxSpecies1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSpecies1ActionPerformed(evt);
            }
        });

        jTextFieldProducts.setText(org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jTextFieldProducts.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton5, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBoxSpecies2.setModel(
            new javax.swing.DefaultComboBoxModel(getSpeciesList())
        );

        jTextFieldReactants.setText(org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jTextFieldReactants.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton6, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jButton6.text")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabelKOn, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jLabelKOn.text")); // NOI18N

        jTextFieldKOn.setText(org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jTextFieldKOn.text")); // NOI18N

        jComboBoxKOn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unit 1", "Unit 2", "Unit 3" }));
        jComboBoxKOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKOnActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jCheckBoxReversible, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jCheckBoxReversible.text")); // NOI18N
        jCheckBoxReversible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxReversibleActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabelKOff, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jLabelKOff.text")); // NOI18N
        jLabelKOff.setEnabled(false);

        jTextFieldKOff.setText(org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jTextFieldKOff.text")); // NOI18N
        jTextFieldKOff.setEnabled(false);

        jComboBoxKOff.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unit 1", "Unit 2", "Unit 3" }));
        jComboBoxKOff.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(jButtonDialogCancle, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jButtonDialogCancle.text")); // NOI18N
        jButtonDialogCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDialogCancleActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButtonDialogOK, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jButtonDialogOK.text")); // NOI18N
        jButtonDialogOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDialogOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxReversible)
                                    .addGroup(jDialog1Layout.createSequentialGroup()
                                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelKOn)
                                            .addGroup(jDialog1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldKOn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBoxKOn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(68, 68, 68)
                                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jDialog1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldKOff, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBoxKOff, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelKOff))))
                                .addGap(0, 153, Short.MAX_VALUE))
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addGroup(jDialog1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxSpecies1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5))
                                    .addComponent(jTextFieldProductsSum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addGroup(jDialog1Layout.createSequentialGroup()
                                        .addComponent(jComboBoxSpecies2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldReactants, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6))
                                    .addComponent(jTextFieldReactantsSum)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDialogOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDialogCancle)))
                .addContainerGap())
        );

        jDialog1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxSpecies1, jComboBoxSpecies2});

        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProductsSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldReactantsSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSpecies1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSpecies2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldReactants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKOn)
                    .addComponent(jLabelKOff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxKOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxKOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldKOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxReversible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDialogCancle)
                    .addComponent(jButtonDialogOK))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jLabel1.AccessibleContext.accessibleName")); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        org.openide.awt.Mnemonics.setLocalizedText(jButtonAddSpecies, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jButtonAddSpecies.text")); // NOI18N
        jButtonAddSpecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSpeciesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButtonDeleteSpecies, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jButtonDeleteSpecies.text")); // NOI18N
        jButtonDeleteSpecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSpeciesActionPerformed(evt);
            }
        });

        jTableReactions.setModel(reactionsTableModel);
        jScrollPane2.setViewportView(jTableReactions);
        jTableReactions.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jTableReactions.columnModel.title0_2")); // NOI18N
        jTableReactions.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jTableReactions.columnModel.title1_2")); // NOI18N
        jTableReactions.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jTableReactions.columnModel.title2_2")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButtonDeleteReaction, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jButtonDeleteReaction.text")); // NOI18N
        jButtonDeleteReaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteReactionActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButtonAddReaction, org.openide.util.NbBundle.getMessage(MyTestModelToolTopComponent.class, "MyTestModelToolTopComponent.jButtonAddReaction.text")); // NOI18N
        jButtonAddReaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddReactionActionPerformed(evt);
            }
        });

        jTableSpecies.setModel(speciesTableModel);
        jTableSpecies.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableSpeciesPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(jTableSpecies);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButtonAddSpecies)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteSpecies)
                        .addGap(329, 329, 329)
                        .addComponent(jButtonAddReaction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteReaction)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddReaction)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddSpecies)
                        .addComponent(jButtonDeleteSpecies)
                        .addComponent(jButtonDeleteReaction)))
                .addGap(178, 178, 178))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    
     
    /**
     * This method deletes a specie from the table
     * @param evt 
     */
    private void jButtonDeleteSpeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSpeciesActionPerformed
        int row = jTableSpecies.getSelectedRow();
        
        if(row >= 0) {
            speciesTableModel.removeRow(row);
        }
    }//GEN-LAST:event_jButtonDeleteSpeciesActionPerformed
    
    private void jButtonAddReactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddReactionActionPerformed
        jComboBoxSpecies1.setModel(new javax.swing.DefaultComboBoxModel(getSpeciesList()));
        jComboBoxSpecies2.setModel(new javax.swing.DefaultComboBoxModel(getSpeciesList()));
        jDialog1.setVisible(true);
        
    }//GEN-LAST:event_jButtonAddReactionActionPerformed
    
    private void jButtonAddSpeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSpeciesActionPerformed
        speciesTableModel.insertRow(0, new Object[] {""});
    }//GEN-LAST:event_jButtonAddSpeciesActionPerformed

    private void jComboBoxSpecies1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSpecies1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSpecies1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String products = jTextFieldProductsSum.getText();
        products += (products == null || products.isEmpty())? "" : " + ";
        products += jTextFieldProducts.getText() + " " + jComboBoxSpecies1.getSelectedItem().toString();
        
        jTextFieldProductsSum.setText(products);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBoxKOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKOnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKOnActionPerformed

    private void jCheckBoxReversibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxReversibleActionPerformed
        setKoff(jCheckBoxReversible.isSelected());
    }//GEN-LAST:event_jCheckBoxReversibleActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String reactants = jTextFieldReactantsSum.getText();
        reactants += (reactants == null || reactants.isEmpty())? "" : " + ";
        reactants += jTextFieldReactants.getText() + " " + jComboBoxSpecies2.getSelectedItem().toString();
        
        jTextFieldReactantsSum.setText(reactants);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonDialogCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDialogCancleActionPerformed
        clearDialog();
    }//GEN-LAST:event_jButtonDialogCancleActionPerformed

    private void jButtonDialogOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDialogOKActionPerformed
        reactionsTableModel.addRow(new Object []{ 
            jTextFieldReactantsSum.getText(), 
            jTextFieldKOn.getText(), 
            jTextFieldProductsSum.getText()});
        jTableReactions.setModel(reactionsTableModel);
        
        clearDialog();
    }//GEN-LAST:event_jButtonDialogOKActionPerformed

    private void jButtonDeleteReactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteReactionActionPerformed
        int row = jTableReactions.getSelectedRow();
        
        if(row >= 0) {
            reactionsTableModel.removeRow(row);
        }
    }//GEN-LAST:event_jButtonDeleteReactionActionPerformed

    private void jTableSpeciesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableSpeciesPropertyChange
        if("tableCellEditor".equals(evt.getPropertyName())){
            getMyTestModelTool().setSpecies(getSpeciesList());
        }
    }//GEN-LAST:event_jTableSpeciesPropertyChange
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonAddReaction;
    private javax.swing.JButton jButtonAddSpecies;
    private javax.swing.JButton jButtonDeleteReaction;
    private javax.swing.JButton jButtonDeleteSpecies;
    private javax.swing.JButton jButtonDialogCancle;
    private javax.swing.JButton jButtonDialogOK;
    private javax.swing.JCheckBox jCheckBoxReversible;
    private javax.swing.JComboBox jComboBoxKOff;
    private javax.swing.JComboBox jComboBoxKOn;
    private javax.swing.JComboBox jComboBoxSpecies1;
    private javax.swing.JComboBox jComboBoxSpecies2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelKOff;
    private javax.swing.JLabel jLabelKOn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableReactions;
    private javax.swing.JTable jTableSpecies;
    private javax.swing.JTextField jTextFieldKOff;
    private javax.swing.JTextField jTextFieldKOn;
    private javax.swing.JTextField jTextFieldProducts;
    private javax.swing.JTextField jTextFieldProductsSum;
    private javax.swing.JTextField jTextFieldReactants;
    private javax.swing.JTextField jTextFieldReactantsSum;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void clearDialog() {
        jTextFieldProductsSum.setText("");
        jTextFieldReactants.setText("");
        jTextFieldReactantsSum.setText("");
        jTextFieldReactants.setText("");
        jTextFieldKOn.setText("");
        jTextFieldKOff.setText("");
        jCheckBoxReversible.setSelected(false);
        setKoff(false);
        
        jDialog1.setVisible(false);
    }

    private void setKoff(boolean enabled) {
        jComboBoxKOff.setEnabled(enabled);
        jTextFieldKOff.setEnabled(enabled);
        jLabelKOff.setEnabled(enabled);
    }
}
